kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: codewind-operator-cluster
rules:

  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["get", "watch", "list", "create", "update", "delete", "patch", "use"]

  - apiGroups: [""]
    resources: ["deployments/finalizers"]
    verbs: ["watch", "get","list","create", "update","delete","patch"]

  - apiGroups: [""]
    resources: ["events"]
    verbs: ["list", "watch", "create", "update", "patch"]

  - apiGroups: [""]
    resources: ["ingresses","ingresses/status"]
    verbs: ["delete","create","patch","get","list","update","watch","use"]

  - apiGroups: [""]
    resources: ["podsecuritypolicies"]
    verbs: ["delete","create","patch","get","list","update","watch","use"]

  - apiGroups: [""]
    resources: ["namespaces"]
    verbs: ["get","list","create","delete","patch"]

  - apiGroups: [""]
    resources: ["persistentvolumes"]
    verbs: ["get", "list", "watch", "create", "delete"]

  - apiGroups: [""]
    resources: ["persistentvolumeclaims",persistentvolumeclaims/finalizers,"persistentvolumeclaims/status"]
    verbs: ["*","create", "delete", "deletecollection", "get", "list", "patch", "watch", "update"]

  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "watch", "list", "create", "delete"]

  - apiGroups: [""]
    resources: ["pods/exec","pods/log","pods/portforward"]
    verbs: ["get","list","create","delete","watch"]

  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "watch", "list", "create", "patch","update", "delete", "deletecollection"]

  - apiGroups: [""]
    resources: ["serviceaccounts"]
    verbs: ["get","patch"]

  - apiGroups: [""]
    resources: ["services"]
    verbs: ["get","list","create","delete","patch"]

  - apiGroups: [""]
    resources: ["services/finalizers"]
    verbs: ["*"]

  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["watch", "get", "list", "create", "update", "delete", "patch"]

  - apiGroups: ["apps"]
    resources: ["deployments/finalizers"]
    verbs: ["watch", "get","list","create", "update","delete","patch"]

  - apiGroups: ["apps"]
    resources: ["replicasets"]
    verbs: ["delete", "get", "list","update"]

  - apiGroups: ["apps"]
    resources: ["replicasets/finalizers"]
    verbs: ["get","list","update","delete"]

  - apiGroups: ["build.openshift.io"]
    resources: ["buildconfigs"]
    verbs: ["create", "delete", "deletecollection", "get", "list", "patch", "update", "watch"]

  - apiGroups: ["icp.ibm.com"]
    resources: ["images"]
    verbs: ["get","list","create","watch"]

  - apiGroups: ["extensions"]
    resources: ["deployments","deployments/finalizers"]
    verbs: ["watch", "get","list","create", "update","delete","patch"]

  - apiGroups: ["extensions"]
    resources: ["ingresses","ingresses/status"]
    verbs: ["delete","create","patch","get","list","update","watch","use"]

  - apiGroups: ["extensions"]
    resources: ["podsecuritypolicies"]
    verbs: ["delete","create","patch","get","list","update","watch","use"]

  - apiGroups: ["extensions"]
    resources: ["replicasets","replicasets/finalizers"]
    verbs: ["get","list","update","delete"]

  - apiGroups: ["image.openshift.io"]
    resources: ["images", "imagestreams"]
    verbs: ["create", "delete", "deletecollection", "get", "list", "patch", "update", "watch"]

  - apiGroups: ["image.openshift.io"]
    resources: ["imagesignatures"]
    verbs: ["create", "delete"]

  - apiGroups: ["image.openshift.io"]
    resources: ["imagestreamimages"]
    verbs: ["get"]

  - apiGroups: ["image.openshift.io"]
    resources: ["imagestreamimports", "imagestreammappings"]
    verbs: ["create"]

  - apiGroups: ["image.openshift.io"]
    resources: ["imagestreamtags"]
    verbs: ["create", "delete", "get", "list", "patch", "update"]

  - apiGroups: ["apps.openshift.io"]
    resources: ["deploymentconfigs"]
    verbs: ["create", "delete", "deletecollection", "get", "list", "patch", "update", "watch"]

  - apiGroups: ["project.openshift.io"]
    resources: ["projectrequests"]
    verbs: ["create", "list"]

  - apiGroups: ["project.openshift.io"]
    resources: ["projects"]
    verbs: ["create", "delete", "get", "list", "watch", "patch", "update", "watch"]

  - apiGroups: ["rbac.authorization.k8s.io"]
    resources: ["clusterroles"]
    verbs: ["get","create","list","patch","watch","delete"]

  - apiGroups: ["rbac.authorization.k8s.io"]
    resources: ["clusterrolebindings"]
    verbs: ["get","create","list","update","delete","patch","watch"]

  - apiGroups: ["rbac.authorization.k8s.io"]
    resources: ["rolebindings"]
    verbs: ["get","list","create","watch","patch","update"]

  - apiGroups: ["rbac.authorization.k8s.io"]
    resources: ["roles"]
    verbs: ["create","get","patch","list", "watch"]

  - apiGroups: ["route.openshift.io"]
    resources: ["routes","routes/custom-host"]
    verbs: ["watch","get","list","create","update","delete","deletecollection","patch"]

  - apiGroups: ["security.openshift.io"]
    resources: ["securitycontextconstraints"]
    verbs: ["use"]

  - apiGroups: ["storage.k8s.io"]
    resources: ["storageclasses"]
    verbs: ["get", "list", "watch"]
